---
- name: registering the result of that command `hostname` as a variable. 
  command: hostname
  register: hostname

- name: Display the HOSTNAME.
  debug:
    msg: "HOSTNAME: {{ hostname.stdout }}"
