---
# Adapt to different download methods.
- debug:
    msg: "{{ package.remote_src }}"

- name: Set fact for download method.
  set_fact:
    down_method: "get_url"
  when: package.remote_src is match("http[s]?://")

- include_tasks: "use_{{ down_method | default('synchronize') }}.yml"
